// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa0k1-9Nond0xHvW22H6qs7hs6RPVtt18',
    appId: '1:1048616933365:web:acf6e64a546ad63ab032bc',
    messagingSenderId: '1048616933365',
    projectId: 'flutter-projects-d8ea1',
    authDomain: 'flutter-projects-d8ea1.firebaseapp.com',
    storageBucket: 'flutter-projects-d8ea1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeIlqaSdSNq9Oxd6NDUfZeza_ew6zSy6A',
    appId: '1:1048616933365:android:64af40b499dca4b8b032bc',
    messagingSenderId: '1048616933365',
    projectId: 'flutter-projects-d8ea1',
    storageBucket: 'flutter-projects-d8ea1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2eplghR-2pgODyF3n0H6zJj5EdL8VYPU',
    appId: '1:1048616933365:ios:3059e78a88d95e46b032bc',
    messagingSenderId: '1048616933365',
    projectId: 'flutter-projects-d8ea1',
    storageBucket: 'flutter-projects-d8ea1.firebasestorage.app',
    iosBundleId: 'com.example.notificationsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2eplghR-2pgODyF3n0H6zJj5EdL8VYPU',
    appId: '1:1048616933365:ios:3059e78a88d95e46b032bc',
    messagingSenderId: '1048616933365',
    projectId: 'flutter-projects-d8ea1',
    storageBucket: 'flutter-projects-d8ea1.firebasestorage.app',
    iosBundleId: 'com.example.notificationsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa0k1-9Nond0xHvW22H6qs7hs6RPVtt18',
    appId: '1:1048616933365:web:961ba870652f3637b032bc',
    messagingSenderId: '1048616933365',
    projectId: 'flutter-projects-d8ea1',
    authDomain: 'flutter-projects-d8ea1.firebaseapp.com',
    storageBucket: 'flutter-projects-d8ea1.firebasestorage.app',
  );
}
